### ISSUE TITLE
TrioDeprecationWarning: trio.MultiError is deprecated

### ISSUE THREAD

**Issue by brownbag270** [WildSiphon/Mailfoguess#1]
This appears to be for verifying Gmail permutations:

```
usr/local/lib/python3.10/dist-packages/anyio/_backends/_trio.py:164: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)

  class ExceptionGroup(BaseExceptionGroup, trio.MultiError):

list index out of range

list index out of range

list index out of range

list index out of range

list index out of range

list index out of range

list index out of range

list index out of range

list index out of range

list index out of range

list index out of range

```

**Comment by smurfix** [comment]
You need to update anyio – to the current master from git, since 4.0 has not yet been released.
Alternately, temporarily downgrade Trio to 0.21.

**Comment by WildSiphon** [comment]
I can't reproduce your issue. I need more informations to investigate:
+ did you install the requirements inside a virtual environment ?
+ what version of `holehe`, `httpx` and `trio` do you use ?

Here's my packages version:
```
$ pip list | grep "holehe\|httpx\|trio"
holehe           1.61
httpx            0.23.1
trio             0.22.0
```

**Comment by brownbag270** [comment]
Hi WildSiphon,

Apologies for the delay. I have these:

```
osint@osint:~/Desktop$ pip list | grep "holehe\|httpx\|trio"

holehe                         1.61

httpx                          0.23.3

trio                           0.22.0

trio-websocket                 0.9.2

```

**Comment by WildSiphon** [comment]
> You need to update anyio – to the current master from git, since 4.0 has not yet been released.

I didn't see this comment before. Thanks for the help 🙏

> Alternately, temporarily downgrade Trio to 0.21.

You could do this or temporarily use a lower version of python (< 3.11).
