### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by oasn** [WildSiphon/Mailfoguess#2]
Hello,

i am new and don't really know how to fix
" UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 277: character maps to <undefined> "

Can you help me out, please? Thank you.

**Comment by WildSiphon** [comment]
Can you provide more informations ?

- When this happened ? (during installation, when looking for someone...) 
- What did you try ?
- Can you provide a bigger stack trace or a screenshot of the error ? I dont even know which part of the code failed...

**Comment by biggermine** [comment]
it happens after it's installed when i try to execute python3 mailfoguess.py.
Traceback (most recent call last):
  File "d:\Osint Tools\Mailfoguess\mailfoguess.py", line 286, in <module>
    print(open("assets/banner.txt", "r").read())
  File "D:\python 3.10\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 279: character maps to <undefined>

**Comment by WildSiphon** [comment]
It seems that the encoding I used for the banner causes the error. You can still use my tool with the option `--no-banner` until I fix this.

Thanks for reporting this.
